# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83962d6034bda0d379ead5eb7fb100ec4951ed422ec4266d9dd5bc25f0d1ed1591e3982a8d3cd89dd204c6f31ff683d7c9884cd17783329e5dc69bb0109f1234

test:
  secret_key_base: 72a9c1b76ef52ec62f052c451c3ce4004e26c53dfe1a7ee81a8759274ccbc87cfa183aa61b9cec6c3c3eaf7c6bbe7b8d15c5e242abdb83e4896b27aa1aac4721

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
